[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "pip install -r requirements-light.txt"
]

[phases.build]
cmds = ["chmod +x start-light.sh"]

[start]
cmd = "./start-light.sh"
