[phases.setup]
nixPkgs = ["python39", "curl"]

[phases.install]
cmds = [
  "curl -fsSL https://ollama.com/install.sh | sh",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "./start.sh"
